### ISSUE TITLE
Crashing when creating world

### ISSUE THREAD

**Issue by FR00TP3NCH** [ABU008/Legacy-Bob#5] opened 2024-10-13 12:02 UTC
So everytime I load into a world (in forge and fabric) it just crashes, i'll send a snip-it of the crash report:
https://pastebin.com/G5ruTrUx

**Comment by ABU008** [comment] 2024-10-17 10:26
interesting, can you send me a list of your mods and also send me your mod loader and mod loader version so I can reproduce this error.

**Comment by FR00TP3NCH** [comment] 2024-10-20 11:49
it was on 1.20.6 and i was using just the defaults, i'll try to see if it still happens

**Comment by FR00TP3NCH** [comment] 2024-10-20 11:52
yeah it still happens but it stops when i install embeddium on neoforge
i'm gonna check what happens on fabric

**Comment by FR00TP3NCH** [comment] 2024-10-20 11:54
> it was on 1.20.6 and i was using just the defaults, i'll try to see if it still happens

i was using just legacybob

**Comment by FR00TP3NCH** [comment] 2024-10-20 11:55
okay i crash on fabric with fabric api and legacybob and when i install sodium it stops

**Comment by ABU008** [comment] 2024-10-20 11:57
that's interesting because during testing I never got any crashes with just bare LegacyBob. I will check and hopefully resolve the bug, if I can't then I will add sodium as a list of dependencies.

**Comment by ABU008** [comment] 2024-10-28 12:19
Fixed in LegacyBob 1.3

**Closed as completed by ABU008** 2024-10-28 12:19 UTC
Labels: bug
